Updated Gradle to 7.4.2
hyphanet/fred pull request #766
Opened 2022-04-17 16:27 UTC by marine-master

Changes:

- The Gradle wrapper has been upgraded to version 7.4.2.
- build.gradle has been fully updated for Gradle 7. There are no warnings.
- Gradle's own dependency verification mechanism has taken the place of "gradle-witness".
- Task "test" and "build" are now working under Java 17.
- Additional comments have been added.

2023-10-19 11:41 UTC, ArneBab requested changes

2023-10-19 11:41 UTC, ArneBab commented on gradle/verification-metadata.xml
> +            <sha512 value="440e81a7c7ded403c3190d81dc372a6559ffc4f9cb13d7d07328f25c34887f2df594652aeb04308ded8b473a5422ef45c58c7d6d2677ce541372fb52afc7a792" origin="Generated by Gradle"/>
This cannot be matched with the dependencies.properties, which is the actual source of truth.

Can Gradle include the sha256 hash instead?

dependencies.properties includes this about jna-platform:

```
jna-platform.filename=jna-platform-4.5.2.jar
jna-platform.sha256=f1d00c167d8921c6e23c626ef9f1c3ae0be473c95c68ffa012bc7ae55a87e2d6
```

We need an entry that connects the gradle-hash to the dependencies.properties hash to be able to switch.

2023-10-19 11:41 UTC, ArneBab commented
Thank you for the work on updating gradle! I’m sorry that I didn’t answer earlier: I had missed your PR.

2024-05-10 08:15 UTC, hernic commented
@ArneBab @Bombe hello, it could be nice for Virtual Threads if this PR could be resolved and merged (needed)

2024-08-05 17:50 UTC, closed without merging

2024-08-05 17:50 UTC, ArneBab commented
Closing in favor of #827 which already uses sha256 so its validation can be checked against dependencies.properties.

@hernic I hope #827 will move forward.