Replace deprecated html tag
hyphanet/fred pull request #935
Opened 2024-02-10 20:19 UTC by Juiceman

2024-02-10 21:13 UTC, Bombe requested changes

2024-02-10 21:13 UTC, Bombe commented on src/freenet/clients/http/staticfiles/js/m3u-player.js
I believe this file is protected by a checksum somewhere, that checksum needs to be updated as well.

2024-02-10 21:13 UTC, Bombe commented on src/freenet/clients/http/staticfiles/freenetjs/hosted.html
Wow, this whole file looks completely broken. Is this actually still used anywhere? @ArneBab, do you know more about this?

2024-02-10 23:55 UTC, Juiceman commented on src/freenet/clients/http/staticfiles/js/m3u-player.js
Nice catch!
Curiously, the original file did not match the checksum in the code.
private static String generateRestrictedScriptSrc() {
		// TODO: auto-generate these hashes from the path to the source file
		String[] allowedScriptHashes = new String[] {
				"sha256-RY9OjosvFxocXEmcUqBJ2v1KByDRdUgnGHYSL3Qx/t8=" // freenet/clients/http/staticfiles/js/m3u-player.js
		};
![image](https://github.com/hyphanet/fred/assets/77873/439a6f0f-2645-49f0-831e-5017a218acf2)

2024-02-11 12:05 UTC, ArneBab commented on src/freenet/clients/http/staticfiles/js/m3u-player.js
The required checksum formatting to work in the browser is `sha256sum m3u-player.js | cut -d " " -f 1 | xxd -r -p | base64`.  On my computer this matches — if this does not match for you: did the linebreaks get changed on checkout?

2024-02-11 12:07 UTC, ArneBab commented on src/freenet/clients/http/staticfiles/freenetjs/hosted.html
I think GWT was for web-pushing and has not been used for many years. I don’t think it still works, but someone needs to check that before removing it.

2024-02-11 20:30 UTC, Juiceman commented on src/freenet/clients/http/staticfiles/js/m3u-player.js
If you say it matches I believe you. I do not have that command on Windows to replicate it.

I will back this commit out since it only fixed a spelling typo in a comment.

2024-02-17 11:36 UTC, Bombe approved these changes

2024-03-16 20:58 UTC, merged

2024-03-16 21:00 UTC, ArneBab commented
Thank you for your PR and review! Merged.