Add image/webp type
hyphanet/fred pull request #961
Opened 2024-05-01 13:21 UTC by torusrxxx

This adds the image/webp format. I already has a WebP content filter working, just without tests. Nevertheless, it's good to have the MIME type added first.

2024-05-03 22:09 UTC, bertm requested changes
Thank you for investing the time to get this filter started!

There are a few areas where improvements are needed, especially related to: public API surface, restriction of resource usage, and chunk boundary checks. I hope these comments are helpful, feel free to discuss any thoughts!

2024-05-03 22:09 UTC, bertm commented on src/freenet/client/filter/WebPFilter.java
> +			output.writeInt(((size & 0xff000000) >> 24) | ((size & 0x00ff0000) >> 8) | ((size & 0x0000ff00) << 8) | ((size & 0x000000ff) << 24));
We cannot all of a sudden emit less bytes than were specified in the top-level RIFF header. Any missing bytes must be accounted for, for instance by appending a JUNK chunk to the end of the file (if the number of skipped bytes allows for that). Chunk padding should also be taken into account when the chunk size ends up being an odd number.

In short, as long as it is not truly needed on packet level, having this flexibility is not yet worth the effort.

2024-05-04 10:26 UTC, torusrxxx commented
Thanks for your rapid reviews, all have been fixed!

2024-05-04 10:29 UTC, torusrxxx commented on src/freenet/client/filter/RIFFFilter.java
> +			 // FIXME Video with more than 2 GiB data need unsigned format
readInt() gives us negative values, and I don't think we really can filter 2GB videos in JVM while browsing a freesite

2024-05-14 14:53 UTC, torusrxxx commented on src/freenet/client/filter/RIFFFilter.java
> +				if((ckSize & 1) != 0) {
Thanks for you suggestion, it has been fixed. A second test image with alpha channel containing a RIFF chunk of odd size (the ALPH chunk) is added to the tests, to make sure this case is correctly handled.

2024-05-14 14:57 UTC, torusrxxx commented on test/freenet/client/filter/webp/too_big.not_webp
The invalid files have all been converted to Java code constructing them, to make it clear the way it is malformed.

2024-05-14 15:00 UTC, torusrxxx commented on src/freenet/client/filter/WebPFilter.java
> +			if(((ctx.VP8XFlags & 3) != 0) || ((ctx.VP8XFlags & 0xff800000) != 0)) {
This have been fixed. I also have to mention the values of these flags do not correspond to actual definition in libwebp, so I got the correct values of these constants directly from libwebp in the fixed code.

2024-05-14 15:04 UTC, torusrxxx commented on src/freenet/client/filter/RIFFFilter.java
> +			} while(readFilterChunk(fccType, ckSize, context, in, out, charset, otherParams, schemeHostAndPort, cb));
It has been fixed. Multiple tests, including this test, have been added, and all of these tests are passed. I also added a test to make sure appending an additional byte to a valid image results in an invalid image.

2024-05-14 15:13 UTC, torusrxxx commented on src/freenet/client/filter/WebPFilter.java
> +			if(width > 16384 || height > 16384) {
A canvas size larger than 14 bits is not supported by VP8 compression. And we don't support VP8L codec and animation at this time. Therefore there is no way to define a bigger canvas. The VP8L codec and animation could support a larger canvas. It will be lifted when these are supported.

Supporting VP8L codec properly would mean we need to parse the image using the vulnerable codec and try to catch an exception. However, knowingly using vulnerable code is itself a security risk. This needs further discussion.

2024-06-12 14:26 UTC, ArneBab commented
@bertm is this review ready to be merged?

2024-09-01 22:05 UTC, ArneBab commented
> > @bertm is this PR ready to be merged?
> 
> @bertm ping

@bertm ping

2024-09-12 21:58 UTC, ArneBab approved these changes
The current state looks good to me, the review comments by @bertm are addressed, so we can merge it for 1499.

Thank you very much!

2024-09-22 10:57 UTC, merged

2024-09-22 10:58 UTC, ArneBab commented
merged — thank you! :heart: