Gradle update to 8.9
hyphanet/fred pull request #977
Opened 2024-09-14 09:05 UTC by ArneBab

2024-09-16 20:25 UTC, Bombe requested changes

2024-09-16 20:25 UTC, Bombe commented on build.gradle
> +    testImplementation "org.hamcrest:hamcrest-core:2.2"
These are not the latest versions. `junit:junit` is at 4.13.2, and `org.hamcrest:hamcrest` is at 3.0 (and doesn’t need the split libraries anymore).

2024-09-17 06:14 UTC, Bombe commented on build.gradle
> +    testImplementation "org.hamcrest:hamcrest-core:2.2"
> I updated junit now, but hamcrest caused problems with validation.

```
testImplementation('junit:junit:4.13.2') {
    exclude group: 'org.hamcrest', module: 'hamcrest-core'
}
testImplementation("org.mockito:mockito-core:1.9.5") {
    exclude group: 'org.hamcrest', module: 'hamcrest-core'
}
```

And maybe we should decide at some point which kind of Strings we want to use in `build.gradle`… 😄

2024-09-22 11:43 UTC, merged

2024-09-22 11:47 UTC, ArneBab commented on build.gradle
> +    testImplementation 'junit:junit:4.13.2'
I restored those for next. thank you!

2024-09-22 11:47 UTC, ArneBab commented
merged — thank you for your reviews!