Fix junit version
hyphanet/fred pull request #978
Opened 2024-09-16 08:25 UTC by chris-ch

Along with junit version upgraded to 4.13 (gradle test was failing) and hamcrest updated to 3.0, added Codespace config for easier dev onboarding.

2024-09-16 20:16 UTC, Bombe requested changes

2024-09-16 20:16 UTC, Bombe commented on build.gradle
> +    testImplementation 'junit:junit:4.13'
Latest JUnit version is 4.13.2. Any particular reason you’re not updating to the latest version?

2024-09-16 20:16 UTC, Bombe commented on build.gradle
> +    testImplementation "org.hamcrest:hamcrest-library:3.0"
Hamcrest isn’t being split up anymore. Both `org.hamcrest:hamcrest-library` and `org.hamcrest:hamcrest-core` are now basically empty JAR files that both _depend_ on `org.hamcrest:hamcrest` in order to get Maven and Gradle to do the right thing. We should cut out the middleman here.

2024-09-16 20:16 UTC, Bombe commented on gradle/verification-metadata.xml
Hmm, what branch did you base your pull request on? My `gradle/verification-metadata.xml` already contains keys for both hamcrest and JUnit…

2024-09-16 20:16 UTC, Bombe commented on .vscode/settings.json
Settings for your local IDE do not belong in version control.

2024-09-16 20:16 UTC, Bombe commented on .github/dependabot.yml
This does not belong in this pull request.

2024-09-16 20:16 UTC, Bombe commented on .devcontainer/devcontainer.json
This also looks quite unrelated. Please don’t mix unrelated features in pull requests, that just makes it more confusing and more complicated to get anything done.

2024-09-17 06:43 UTC, closed without merging

2024-09-17 07:02 UTC, chris-ch commented
I re-forked the project, starting from scratch completely and from the "next" branch, the jar build is working:
```
$ ./gradlew jar
```

But then the tests fail:
```
@chris-ch ➜ /workspaces/fred (next) $ ./gradlew --parallel test

> Task :compileTestJava FAILED
/workspaces/fred/test/freenet/client/filter/TheoraBitstreamFilterTest.java:12: error: cannot find symbol
import static org.junit.Assert.assertThrows;
^
  symbol:   static assertThrows
  location: class Assert
/workspaces/fred/test/freenet/support/api/BooleanCallbackTest.java:4: error: cannot find symbol
import static org.junit.Assert.assertThrows;
^
  symbol:   static assertThrows
  location: class Assert
/workspaces/fred/test/freenet/support/SimpleFieldSetTest.java:20: error: cannot find symbol
import static org.hamcrest.Matchers.anEmptyMap;
^
  symbol:   static anEmptyMap
  location: class Matchers
...
```

My understanding is that we should upgrade the junit version to 4.13 from 4.12, and potentially hamcrest as well?