Add WAV content filter
hyphanet/fred pull request #982
Opened 2024-09-25 13:35 UTC by torusrxxx

WAV PCM audio is such a simple and safe format. RIFF format is supported so why not WAV files?

2024-09-26 19:30 UTC, Bombe commented
That test needs to be at least a dozen tests, and _none_ of them should be green if you remove all the code from the filter! 😄

2024-10-05 22:54 UTC, bertm requested changes

2024-10-05 22:54 UTC, bertm commented on src/freenet/client/DefaultMIMETypes.java
> +		addMIMEType((short)625, "image/heif", "heif");
These change appear to be unrelated to this PR.

2024-10-05 22:54 UTC, bertm commented on src/freenet/client/filter/ContentFilter.java
> +		register(new FilterMIMEType("audio/vnd.wave", "mp3", new String[] {"audio/vnd.wave", "audio/x-wav", "audio/wav", "audio/wave"},
This mentions `"mp3"` even though it is about WAV.

2024-10-05 22:54 UTC, bertm commented on src/freenet/client/filter/WAVFilter.java
> +	class WAVFilterContext {
This class is not used elsewhere, please make it private.

Additionally, the fields in this class should not be declared `public` as they are not effectively accessible outside this class.
Either make them `private`, or of you prefer a more compact look, make them package-private (by just omitting `public`).

2024-10-05 22:54 UTC, bertm commented on test/freenet/client/filter/WAVFilterTest.java
> +	}
Indentation is off in various places in this class. Please either use 4 spaces or 1 tab for indentation, and don't mix both styles.

2024-10-05 22:54 UTC, bertm commented on src/freenet/client/filter/WAVFilter.java
> +					output.writeByte(input.readByte());
Please use braces around if/then/else blocks, even if they are otherwise one single line.

2024-10-05 22:54 UTC, bertm commented on src/freenet/client/filter/WAVFilter.java
> +			if(size != 16 && size != 18 && size != 40) {
What do these magic numbers represent? (please introduce constants with descriptive names)

2024-10-05 22:54 UTC, bertm commented on src/freenet/client/filter/WAVFilter.java
> +			if(ctx.format == WAVE_FORMAT_PCM || ctx.format == WAVE_FORMAT_IEEE_FLOAT || ctx.format == WAVE_FORMAT_ALAW || ctx.format == WAVE_FORMAT_MULAW) {
This condition will always evaluate to true (ctx.format is only written in line 51 and checked immediately after)

2024-10-21 05:03 UTC, ArneBab commented
@Bombe @bertm can you check whether your comments are addressed?

2025-05-10 23:24 UTC, bertm requested changes
@torusrxxx with a few minor adjustments, this should be good to go.

2025-05-10 23:24 UTC, bertm commented on src/freenet/client/filter/WAVFilter.java
> +			passthroughBytes(input, output, size);
The passed-through bytes are format-specific. This would allow passing arbitrary unverified non-audio data.
However, the currently supported formats are uncompressed and should, if at all, only have the first `dwSampleLength` field.
Can we limit the number of passed-through bytes to 4 and ignore whichever bytes remain? Of course this should be adjusted accordingly in the size following the `fmt ` chunk ID.

2025-05-10 23:24 UTC, bertm commented on test/freenet/client/filter/wav/test.wav
This file appears to be `TADA.WAV` taken from Microsoft Windows 3.1 or 3.11.

I am aware that that's 1992 calling, but I could not find any records that Microsoft would have put these sounds in the public domain, so I need to assume this file is still copyrighted and owned by Microsoft Corporation.

Unless this file can be shown to be in the public domain, please replace it with a file that does not infringe any license or copyright.

2025-05-11 16:36 UTC, torusrxxx commented on src/freenet/client/filter/WAVFilter.java
> +			passthroughBytes(input, output, size);
limiting the number of passed-through bytes doesn't guarantee the remaining 00 bytes won't have an effect, so I just discard this entire trunk when the size is not 4.

2025-05-11 16:37 UTC, torusrxxx commented on test/freenet/client/filter/wav/test.wav
I replaced the content with silence

2025-06-24 21:17 UTC, ArneBab commented
@bertm is this good to go?

2025-06-28 10:33 UTC, bertm approved these changes
The testing could be a bit heavier, but the basics are covered.

2025-06-28 19:18 UTC, merged

2025-06-28 19:18 UTC, ArneBab commented
Merged -- thank you!