Update Gradle to 8.11
hyphanet/fred pull request #996
Opened 2024-11-12 21:49 UTC by ArneBab

simply via ./gradlew wrapper --gradle-version 8.11

No other changes.

2024-11-17 13:59 UTC, bertm requested changes

2024-11-22 08:03 UTC, ArneBab commented on gradle/wrapper/gradle-wrapper.jar
Updated — thank you for the catch! That is ignored by .gitignore so I had to `git add -f` it and I had missed that.

2024-11-29 21:50 UTC, ArneBab commented
@bertm is this OK to merge?

2024-11-30 09:44 UTC, bertm approved these changes
Thanks, the checksums do now match as expected :+1:

2024-11-30 20:37 UTC, merged